package Stats;

/**
 * Created by brian on 4/11/16.
 */
public enum GameState {
    PLACE_HOLDER, HANDSHAKE_COMPLETE_SUCCESS, LOGIN, LOGIN_DONE, NEW_USER_LOGIN_DONE, PLAY,
    PLAY_DONE, UPDATE_HEALTH,SET_POSITION, DEATH, LOADING_DONE;
}

